eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8084
spring:
  application:
    name: service-zuul
zuul:
  routes:
    linphone:
      path: /linphone/**
      serviceId: server-linphone
    platform:
      path: /platform/**
      serviceId: server-platform